version: "v1.0.2"
name: TODO-Task
services:
  server:
    build: .
    env_file:
      - .env
    ports: 
      - "7540:7540"
    environment:
      - TODO_PORT=${TODO_PORT}
      - TODO_DBFILE=${TODO_DBFILE}
      - TODO_PASSWORD=${TODO_PASSWORD}
